### ISSUE TITLE
Ignoring the detection will result in a persistent error message that should disappear

### ISSUE THREAD

**Issue by BinaryAlan** [SanderRonde/phpstan-vscode#47] opened 2024-01-25 03:02 UTC
Figure: line 29 :`return $this-> businesscirclelogic-> getPointRelation ($longitude, $latitude)-> toArray () ;` , `-> toArray () ` has been removed, but it still reports an error, because the check was skipped
<img width="1096" alt="image" src="https://github.com/SanderRonde/phpstan-vscode/assets/37968794/b933f684-9c8b-48d7-aa59-a85391e1d880">

**Comment by SanderRonde** [comment] 2024-01-26 13:02
Hmm I'm not really sure what the bug is here. Is the issue that it should be checking the file but isn't? Could it be that the file is not yet saved to disk maybe? If it's correct in not checking and the issue is that it doesn't remove the squiggly lines when removing the offending line, that's something I can't really fix. The extension tells VSCode where an issue is and VSCode tries its best to position the error. It's really hard to detect when an offending line was removed and when an issue has been fixed by the user. The only real way to check that is to re-check the file with PHPStan, which only happens on-save.

**Comment by BinaryAlan** [comment] 2024-01-31 02:19
Is it possible that the file was modified and saved during phpstan execution, but this change was skipped and the phpstan check was not performed again ?

**Comment by SanderRonde** [comment] 2024-02-01 00:34
Theoretically not. Any running check should be cancelled as soon as the file changes and a new one should be queued.

Does this happen often or rarely? And do you have autosave on?

**Comment by BinaryAlan** [comment] 2024-02-01 00:56
It happens frequently, and files are automatically saved when they lose focus

**Comment by SanderRonde** [comment] 2024-02-04 14:54
Can you check out the pre-release version of the extension? Quite a lot has changed and it should be a lot more robust now. It does now always check the whole project at a time instead of just the file and has more guards for invalidating running checks when a file changes. Thanks!

**Comment by BinaryAlan** [comment] 2024-03-01 09:07
It's working fine now, thanks

**Comment by SanderRonde** [comment] 2024-03-01 10:23
Awesome, good to hear. I'll close this issue then

**Closed as completed by SanderRonde** 2024-03-01 10:23 UTC
