### ISSUE TITLE
High CPU usage has persisted since v3.2.2

### ISSUE THREAD

**Issue by ani2life** [SanderRonde/phpstan-vscode#103] opened 2024-09-09 08:49 UTC
- VSCode: 1.93.0
- PHPStan: 1.12.2

After installing the latest version of phpstan-vscode, I encountered an issue with consistently high CPU usage.
When I specify version 3.2.1 of phpstan-vscode, the issue does not occur. The problem starts from version 3.2.2 and above.
I waited for the CPU usage to decrease without doing anything, but the CPU usage did not go down.

**Comment by SanderRonde** [comment] 2024-09-09 09:22
Hmm what does this high CPU usage consist of? Is it a bunch of scans not closing? More scans spawning? Is it maybe the new `diagnose` command running? And, just to be sure, are you really sure that it is broken in `3.2.2` and not `3.2.1`? (if so that would be a great help)

**Comment by ani2life** [comment] 2024-09-09 09:45
<img width="884" alt="phpstan-vscode-3 2 2-cpu" src="https://github.com/user-attachments/assets/e877c3bc-7662-4175-9769-a751c0ba110e">
I just updated the version again and, as shown in the screenshot, the CPU usage of `sanderronde.phpstan-vscode-3.2.4/out/server.js` process remains high.

**Comment by SanderRonde** [comment] 2024-09-09 09:47
Ahhh I thought you meant a process it spawned. I've got a hunch as to what this could be and will look into it. Thanks!

**Comment by SanderRonde** [comment] 2024-09-09 10:27
I can't reproduce it yet, can you help me out by shedding some light into your setup? I'm guessing this is related to the file watcher I added in the new version, it might be doing some really inefficient file watching. So some questions:
- What platform/OS are you using?
- Is there anything special about where you're running VSCode? (for example inside a docker container)
- Are there a lot of files in the repo?
- Could there be something causing file updates to be happening relatively often in the repo?

**Comment by ani2life** [comment] 2024-09-09 11:34
<img width="274" alt="phpstan-files" src="https://github.com/user-attachments/assets/f1f60188-85ed-4589-ba60-61c29495898a">
- macOS: 14.6.1
- VSCode is running normally on local.
- The bottom status bar of VSCode shows that 836 files have been detected.
- If no editing is done, there are no changes to the files in the repository. The CPU usage does not decrease even when doing nothing and staying idle.

**Comment by SanderRonde** [comment] 2024-09-09 11:42
Ah I don't have a mac so it's not super easy to replicate... Can you check whether installing the below versions of the extension also gets rid of the issue? To install them rename them from `.zip` to `.vsix` and drag it into the extensions panel in VSCode.

First option:
- Disables the file watching feature entirely. This should 100% fix the issue.
- File: [phpstan-vscode-3.2.4.zip](https://github.com/user-attachments/files/16929805/phpstan-vscode-3.2.4.zip)

Second option:
- Disables polling, which apparently can cause high CPU usage, but the functionality is preserved
- File: [phpstan-vscode-2-3.2.4..zip](https://github.com/user-attachments/files/16929830/phpstan-vscode-2-3.2.4.zip)

Thanks a lot!

**Comment by ani2life** [comment] 2024-09-09 12:11
I've tested both files multiple times.

First option: No problems. It's normal.

Second option:

<img width="277" alt="스크린샷 2024-09-09 오후 9 03 48" src="https://github.com/user-attachments/assets/7b0b7edc-4d76-4085-a51c-abf96eee498f">

It does not progress at 100% status.
The CPU usage is low, but it is not working.

**Comment by SanderRonde** [comment] 2024-09-09 13:11
I've made some more changes, I think I've fixed this bug now, as well as making the file watching more performant. Can you try this out?

[phpstan-vscode-3-3.2.4.zip](https://github.com/user-attachments/files/16930999/phpstan-vscode-3-3.2.4.zip)

**Comment by ani2life** [comment] 2024-09-09 15:08
> [phpstan-vscode-3-3.2.4.zip](https://github.com/user-attachments/files/16930999/phpstan-vscode-3-3.2.4.zip)

The extension only works when it is first launched, and it does not respond even after saving the files later.

**Comment by SanderRonde** [comment] 2024-09-09 15:12
Hmm I can't seem to replicate that, any chance the logs show something other than this? Could be that the statusbar notification is broken. If you check the `Output` panel in VSCode it should have two `PHPStan` log fields. Can you check both of them for any activity when you save files?

**Comment by rdeago** [comment] 2024-09-09 16:26
> [phpstan-vscode-3-3.2.4.zip](https://github.com/user-attachments/files/16930999/phpstan-vscode-3-3.2.4.zip)

I tested this one too, because I'm having the same problem. What I found out (on a 507-file project):
- PHPStan is very fast, almost istantaneous, at first launch, but reports errors I have already corrected. I'm pretty sure it's using a cache, but I can't find it anywhere.
- On all subsequent launches, a timeout is reported after a few seconds, even with ridicolously long tiemout settings.
- Part of the original problem seemed to be that the extension made a very high number of WMI requests. WmiPrvSE.exe took up to 94% of the CPU (a 13th-gen Core i9 with 24 cores and 32 threads) and if I terminated it there started a flood of spawned WMIC.exe instances. This problem does not occur with the modified extension.

I hope this helps. If you need more info, please feel free to ask.

**Comment by SanderRonde** [comment] 2024-09-09 16:40
Alright that makes it pretty clear that the file-watching I was doing using `chokidar` is just hammering the CPU. In the below release I've fixed the timeout issue and I've disabled the file-watcher entirely. Can you verify that it works? If so I'll release the update right after.

[phpstan-vscode-3.2.4-4.zip](https://github.com/user-attachments/files/16933596/phpstan-vscode-3.2.4-4.zip)

**Comment by rdeago** [comment] 2024-09-09 16:45
Man, that was _fast_! 😂 I'm currently testing it and the timeout issue is gone. Stay tuned...

**Comment by rdeago** [comment] 2024-09-09 16:48
All right, it stopped reporting problems that weren't there any longer.

I received a timeout notification though, this time from the language server; it says 60000s (the timeout value I set) but it had spawned PHPStan little more than 3 minutes earlier.

**Comment by rdeago** [comment] 2024-09-09 16:51
This is the language server's log:
```
[9/9/2024, 18:42:39] [server] Language server ready
[9/9/2024, 18:42:40] [file-watcher] Checking: New document active
[9/9/2024, 18:42:40] [check:1] Check started for project
[9/9/2024, 18:42:41] [server] PHPStan version: PHPStan - PHP Static Analysis Tool 1.12.3

[9/9/2024, 18:42:41] [check:1] Spawning PHPStan with the following configuration:  {"binStr":"d:\\Projects\\{REDACTED}\\vendor\\bin\\phpstan","args":["analyse","-c","d:\\Projects\\{REDACTED}\\phpstan.neon","--error-format=json","--no-interaction","--memory-limit=4G","-a","c:\\Users\\{REDACTED}\\.vscode\\extensions\\sanderronde.phpstan-vscode-3.2.4\\_config\\d4dac11180852301f4f0491c50973647\\autoload.php","-c","c:\\Users\\{REDACTED}\\.vscode\\extensions\\sanderronde.phpstan-vscode-3.2.4\\_config\\d4dac11180852301f4f0491c50973647\\config.neon"]}
[9/9/2024, 18:42:51] [diagnose-get-files] Spawning PHPStan with the following configuration:  {"binStr":"d:\\Projects\\{REDACTED}\\vendor\\bin\\phpstan","args":["diagnose","-c","d:\\Projects\\{REDACTED}\\phpstan.neon","-a","c:\\Users\\{REDACTED}\\.vscode\\extensions\\sanderronde.phpstan-vscode-3.2.4\\_config\\d4dac11180852301f4f0491c50973647\\autoload.php","-c","c:\\Users\\{REDACTED}\\.vscode\\extensions\\sanderronde.phpstan-vscode-3.2.4\\_config\\d4dac11180852301f4f0491c50973647\\config.neon"]}
[9/9/2024, 18:43:50] [diagnose-get-files] PHPStan process exited succesfully
[9/9/2024, 18:45:43] [check:1] PHPStan process exited succesfully
[9/9/2024, 18:45:58] [check:1] Check completed for project, errors= {"fileSpecificErrors":{},"notFileSpecificErrors":[]}
[9/9/2024, 18:45:58] [check:1] PHPStan check timed out after 60000000ms
[9/9/2024, 18:46:32] [file-watcher] Checking: New document active
[9/9/2024, 18:46:32] [fixer-manager] No file changes, not checking
[9/9/2024, 18:47:43] [diagnose-get-files] Spawning PHPStan with the following configuration:  {"binStr":"d:\\Projects\\{REDACTED}\\vendor\\bin\\phpstan","args":["diagnose","-c","d:\\Projects\\{REDACTED}\\phpstan.neon","-a","c:\\Users\\{REDACTED}\\.vscode\\extensions\\sanderronde.phpstan-vscode-3.2.4\\_config\\d4dac11180852301f4f0491c50973647\\autoload.php","-c","c:\\Users\\{REDACTED}\\.vscode\\extensions\\sanderronde.phpstan-vscode-3.2.4\\_config\\d4dac11180852301f4f0491c50973647\\config.neon"]}
[9/9/2024, 18:47:45] [diagnose-get-files] PHPStan process exited succesfully
```

**Comment by SanderRonde** [comment] 2024-09-09 16:51
Alright I'll just remove all non-file-watcher-related changes. If this doesn't fix it I don't know what will :)

[phpstan-vscode-3.2.4-5.zip](https://github.com/user-attachments/files/16933700/phpstan-vscode-3.2.4-5.zip)

**Comment by SanderRonde** [comment] 2024-09-09 16:56
I see that the logs you sent are still using the `diagnose-get-files` logs. That code shouldn't be reachable. To be a bit more sure that you are in fact running the version I sent I've added changed the initial log line to `Language server ready (test-v5)` in the version below. (apart from that it's the exact same as what I sent before)

[phpstan-vscode-3.2.4-5.zip](https://github.com/user-attachments/files/16933749/phpstan-vscode-3.2.4-5.zip)

**Comment by rdeago** [comment] 2024-09-09 17:02
The flood of WMIC processes is back. All with the same command line:

```
wmic.exe PROCESS GET Name,ProcessId,ParentProcessId,Status
```

I don't know whether this is directly caused by your extension, but it stops as soon as I disable it.

**Comment by SanderRonde** [comment] 2024-09-09 17:04
Yeah I'm fairly certain it is, I had added a file watcher before, that seems to be causing this. Can you verify whether you are using the version of the extension I posted by checking the logs? The code that does the file watching is no longer there so theoretically this shouldn't be possible.

**Comment by rdeago** [comment] 2024-09-09 17:10
I'm using your latest verson now (`test-v5` 👍) and the bogus timeout seems gone. The flood of WMIC instances is still there.

Unfortunately I have to go now. I'll be back in a couple hours. Thanks for your help!

**Comment by SanderRonde** [comment] 2024-09-09 17:16
Alright thanks for testing! I'm fairly confident that the WMIC stuff has to be related to the file-watching I released earlier since that's the only code I added in v3.2.2. I've now shipped a version with that code disabled (v3.2.5). Could you maybe validate one more time that that does fix the CPU issue?

**Comment by rdeago** [comment] 2024-09-09 20:41
I'm on version 3.2.6 now. Almost everything seems to work fine: no _faux_ timeouts, no stray PHPStan instances.

The flood of WMIC spawns is still there, but stops as soon as PHPStan is done. I guess their purpose is to monitor the PHPStan process; if that's the case, maybe checking less often (e.g. once a second), at least on Windows systems, might prove a valuable improvement.

Thanks a lot for your prompt response!

**Comment by SanderRonde** [comment] 2024-09-09 21:22
Could you check whether the WMIC spawns also happen when running PHPStan outside of the extension? I don't really know how I'm spawning WMIC processes so would be interesting.

I'll close this issue btw since the main issue seems to have been fixed. Thanks for helping out!

**Closed by SanderRonde** 2024-09-09 21:22 UTC

**Comment by rdeago** [comment] 2024-09-09 22:40
I got it! Take a look at #105.

Thanks again!

**Comment by ani2life** [comment] 2024-09-09 22:46
It works without any issues. Thank you.
